#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; 

PLUGIN_DIR=$(dirname $0)
PLUGIN_EXEC_CMD="plugn trigger"

# Traefik labels setup. Plugin is required to prevent Dokku overwrite.
if [ "$APP" = "uroapp" ]; then
    echo ' --label "traefik.http.routers.uroapp-web-http.rule=Host(\`uroapp.dokku.local\`) && PathPrefix(\`/api/v1\`)"';
fi
if [ "$APP" = "nodeapp" ]; then
    echo ' --label "traefik.http.routers.nodeapp-web-http.rule=Host(\`uroapp.dokku.local\`) && PathPrefix(\`/\`)"';
fi
