#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

APP="$1"; 

PLUGIN_DIR=$(dirname $0)
PLUGIN_EXEC_CMD="plugn trigger"

# Traefik labels setup. Plugin is needed for 'PathPrefix' routing.

# DO NOT change plugin repo name or name in plugin.toml.
# Current plugin starts with 'u' (uro-deploy) so it runs after Dokku internal traefik ('t') plugin.
# This is required to avoid overwrite of custom container labels.

# fallback
uro_root_url="vsekai.local"

uro_root_env="$(config_get --global URO_ROOT_URL)"
[[ -n "${uro_root_env}" ]] && uro_root_url="${uro_root_env}"

if [ "$APP" = "uroapp" ]; then
    echo ' --label "traefik.http.routers.uroapp-web-http.rule=Host(\`'${uro_root_url}'\`) && PathPrefix(\`/api/v1\`)"';
    echo ' --label "traefik.http.routers.uroapp-web-http.middlewares=strip-api-prefix@docker"';
    echo ' --label "traefik.http.middlewares.strip-api-prefix.stripPrefix.prefixes=/api/v1"';
fi
if [ "$APP" = "nodeapp" ]; then
    echo ' --label "traefik.http.routers.nodeapp-web-http.rule=Host(\`'${uro_root_url}'\`) && PathPrefix(\`/\`)"';
fi
